#+TITLE: [[https://komodoplatform.com/wp-content/uploads/2018/06/Komodo-Whitepaper-June-3.pdf][Papier blanc de la crypto Komodo]]
#+AUTHOR: Laurent Garnier

* Introduction à Komodo 
  Le projet Komodo vise à donner aux utilisateurs la liberté de passer
  par la technologie blockchain. Il existe de nombreuses formes de
  liberté que Komodo peut offrir, et nous nous concentrons
  actuellement sur l’autonomisation de deux types d’utilisateurs :
  l’entrepreneur de la chaîne de blocs et l’investisseur moyen de
  crypto-monnaie. Ensemble, notre communauté d’entrepreneurs,
  d’investisseurs et d’autres utilisateurs forme un écosystème
  économique. 

  Le pilier fondamental de l'écosystème de Komodo est la
  sécurité. Komodo fournit une forme de sécurité unique et innovante
  qui est aussi forte que le réseau Bitcoin, mais ne nécessite pas le
  coût incroyable. Chaque membre de l'écosystème de Komodo bénéficie
  des avantages de cette sécurité. L'investisseur en dépend pour un
  usage quotidien. L'entrepreneur compte sur lui pour protéger son
  innovation de blockchain à un coût abordable, même pour les petites
  entreprises et les startups. 

  Une autre des technologies puissantes de Komodo est une nouvelle
  méthode de trading de cryptomonnaies directement d’une personne à
  une autre. C’est un nouveau type d’«échange décentralisé». Notre
  échange décentralisé supprime toutes les formes d’intermédiaires, de
  bons et de services de dépôt fiduciaire. Il s'appuie sur un concept
  sous-jacent appelé «échange atomique» et nous sommes les meneurs de
  cette technologie.

  Notre échange décentralisé alimenté par un échange atomique sert à
  la fois l'investisseur et l'entrepreneur de la chaîne de blocs.

  Pour l'investisseur, ils peuvent négocier des devises sans avoir à
  passer par un échange centralisé, ce qui peut être un processus ardu
  et même dangereux. Ils n'ont pas non plus besoin d'utiliser un
  service de dépôt fiduciaire, un bon d'achat, ni même une pièce de
  monnaie intermédiaire, même pas de Bitcoin. De plus, il n'y a pas de
  processus d'enregistrement requis, ni de limites de retrait. Nous
  prenons actuellement en charge environ 95% des cryptomonnaies
  existantes, y compris les pièces basées sur le protocole Bitcoin,
  les jetons Ethereum et les jetons ERC20 basés sur Ethereum. 

  Pour l'entrepreneur, notre échange décentralisé permet de lancer de
  nouveaux produits dans le monde sans implication des
  intermédiaires. De plus, même les entrepreneurs qui ont déjà
  construit d’autres projets de blockchain en dehors de notre
  écosystème peuvent facilement mettre leur pièce sur notre échange
  décentralisé. La seule exigence est que le produit blockchain ait
  les éléments de sécurité appropriés au cœur du code de la
  blockchain. 

  Komodo intègre également de puissantes fonctionnalités de
  confidentialité dans notre plate-forme. Cela permet à l'investisseur
  d'échanger et d'acheter des biens et services dans le cadre de son
  droit à la vie privée. Cela permet également à l'entrepreneur de
  libérer son produit et de créer des sources de financement auprès
  d'un public qui préfère conserver cette confidentialité.

  Il existe de nombreuses autres technologies et fonctionnalités dans
  l'écosystème de Komodo, et nous assistons à une croissance rapide
  des entrepreneurs et des investisseurs. 

  Ce livre blanc de Komodo propose une discussion approfondie sur les
  fonctions de sécurité uniques de Komodo, notre échange décentralisé,
  la méthode de diffusion des nouveaux produits et nos fonctionnalités
  de confidentialité natives.

  Nous accueillons les commentaires de nos lecteurs. Si vous avez des
  questions ou des préoccupations concernant la lecture de ce
  document, veuillez contacter directement notre équipe. Vous pouvez
  trouver nos coordonnées sur notre site Web d'accompagnement : [[https://komodoplatform.com/]]

* Méthode de sécurité Komodo : preuve de travail différé (DPOW : Delayed Proof Of Work)
** Une discussion fondamentale de la sécurité d'une blockchain
   La forme de sécurité de Komodo s'appelle la technologie de preuve
   de travail différée (dPoW). Il s'appuie sur la forme la plus
   avancée de sécurité de la chaîne de blocs existante, la technologie
   de preuve de travail (PoW). Cette dernière forme de sécurité est la
   méthode utilisée par le réseau Bitcoin. Pour comprendre la valeur
   de la sécurité dPoW de Komodo, nous devons d'abord expliquer
   comment PoW fonctionne et pourquoi il s'agit de la méthode la plus
   sécurisée de maintenance d'une blockchain décentralisée. Nous
   devons également examiner les lacunes de PoW, afin que nous
   puissions comprendre la nécessité de la méthode dPoW de Komodo et
   les avantages qu'elle apporte à la communauté de la blockchain. 

   Pour comprendre comment fonctionne la technologie PoW, nous
   commençons par expliquer les racines qui font du protocole Bitcoin
   un moyen viable de transférer de la valeur en toute sécurité. 


*** Qu'est-ce qu'un mécanisme de consensus ?
**** Le problème de "double dépense"

     La création de la technologie de la chaîne de blocs découle des
     premières études mathématiques du cryptage utilisant la
     technologie informatique. 

     L'un de ces exemples concerne le dispositif de codage de
     l'information "Enigma", inventé par les Allemands à la fin de la
     Première Guerre mondiale. Alan Turing, un agent britannique de
     renseignement, a battu le dispositif Enigma en inventant le
     premier «ordinateur numérique» au monde. This provided enough
     computing power to break Enigma's encryption and discover the
     German secret communications[fn:1].

     Cette première affaire de cryptage a déclenché une course à
     travers le monde pour développer une myriade de formes de
     transfert sécurisé des informations d'un pary à l'autre via la
     technologie informatique. Bien que chaque nouvelle forme de
     chiffrement informatique offrait davantage d’avantages, il
     restait un problème qui empêchait le chiffrement d’être utile
     pour transférer non seulement des informations, mais aussi une
     valeur financière.

     Ce problème est connu sous le nom de problème de «double
     dépense». Le problème réside dans la capacité des ordinateurs à
     dupliquer sans cesse les informations. Dans le cas de la valeur
     financière, il y a trois choses importantes à noter: qui possède
     une valeur spécifique; l'heure à laquelle la personne possède
     cette valeur; l'adresse du portefeuille dans lequel réside la
     valeur. Lors du transfert de valeur financière d’une personne à
     une autre, il est essentiel que si la personne A envoie de
     l’argent à la personne B, la personne A ne soit pas en mesure de
     reproduire le même montant et de le renvoyer à la personne C. 

     Le protocole Bitcoin[fn:2], inventé par une personne anonyme (ou des
     personnes) revendiquant le nom de Satoshi Nakamoto, a résolu le
     problème des doubles dépenses. Le code mathématique et
     informatique sous-jacent est à la fois très complexe et
     innovant. Pour les besoins de cet article, nous devons seulement
     nous concentrer sur le seul aspect du protocole Bitcoin qui
     résout le problème des doubles dépenses: le mécanisme de
     consensus. 

     

**** Le mécanisme de consensus fournit une sécurité contre une "double dépense"
**** Un mineur est en compétition pour ajouter des blocs à l'historique du réseau avec une récompense en retour
** La preuve de travail est la forme la plus sécurisée des mécanismes de consensus
*** La vitesse et la puissance sont l'essence
**** L'effet de réseau : la capacité de Bitcoin à dominer commence
*** La règle de la chaîne la plus longue : la "sauce secrète" de la domination PoW (Proof of Work: preuve de travail)
**** Les effets simples de la règle de la plus longue chaîne
**** Le compte des deux blockchains
**** Un conflit d'intérêt interne survient avec le réseau Bitcoin 
**** La règle de la plus longue chaîne : l'historique qui est le plus long en premier, gagne
*** La façon "simple"  de détruire un réseau PoW : l'attaque des 51%
*** La taille est une autre raison derrière le succès actuel de Bitcoin parmi les réseaux PoW
*** La façon "dure" de détruire un réseau PoW : l'attaque de la génèse (Genesis Attack)
**** Une attaque de la génèse sur le réseau Bitcoin
**** Les dangers plus réalistes de l'attaque de la génèse
*** Les problèmes financiers et environnementaux avec tous les réseaux PoW
**** Les réseaux PoW coûtent chers
**** Les mineurs sont libres de miner d'autres réseaux
**** Le premier mécanisme de consensus alternatif : preuve de part ou preuve d'enjeu (Proof of Stake)
**** Les risques de sécurité et les défauts de PoS
**** Un résumé du mécanisme de consensus PoW
** La solution Komodo
*** Résumé du mécanisme de consensus sur la preuve de travail différée (dPoW)
**** Une note sur la technologie Iguana Core de Komodo
**** Une brève discussion sur la sécurité assurée par les noeuds notaires
*** Le processus de notarisation
**** Comprendre les incitations économique et sécuritaire dans le réseau dPoW Komodo
*** Mesures de protection de Komodo en action 
**** Les notarisations fournissent une défense contre l'attaque de 51% et l'attaque de la genèse.
*** Le mécanisme de consensus dPoW est inhérent à tous les actifs des chaînes Komodo

* Les ICO décentralisées (DICO : Decentralized Initial Coin Offering)
** Résumé des DICO
*** Les défis dans les plateformes ICO actuelles
*** Faiblesses spécifiques dans le modèle centralisé ICO
*** Discrimination de tiers via les ICO centralisées
*** Centralisation des technologies ICO : baleines, pirates, et erreurs humaines
*** Pirates et erreurs humaines
** La solution Komodo 
*** Les DICO
*** Le processus de création d'une nouvelle blockchain dans l'écosystème Komodo 
**** La première commande pour créer une nouvelle pièce 
*** Les fonctionnalités de la nouvelle chaîne d'actif
*** Générer et miner les pièces
**** L'approvisionnement total en pièces est distribué dans le bloc de la génèse
*** Notarisation de la chaîne Komodo principale
*** La distribution des pièces 
**** Les essais et les déplacements de la méthode ICO centralisée
*** Entrer dans les dICO
**** Alimenté par les technologies Komodo BarterDEX et Jumblr
**** Les nombreuses solutions du modèle dICO: sécurité, confidentialité, décentralisation et liberté.
* Barterdex place de marché décentralisée ou la puissance d'échange atomique Komodo
** Résumé (BarterDEX)
*** Introduction
**** Les débuts et les voyages des échanges décentralisés
**** BarterDEX : une solution complète
**** Améliorations récentes dans BarterDEX
*** Technologie BarterDEX
**** Correspondance d'ordre
**** Correspondance des commandes avec les nœuds à relais complet et sans relais
**** La technologie Jumblr ajoute de l'intimité
**** Iguana Core fournit la base de notre fonctionnalité "adresse intelligente ("Smart Address")
*** Les UTXO : un concept insaisissable, mais fondamental.
**** Comparaison entre les UTXO et les monnaies fiat
**** Compréhension des crypto-monnaies et leurs UTXOs
*** Trading sur BarterDEX 
**** Comment BarterDEX traite les offres de commande et les UTXOs
*** Explications détaillées du processus BarterDEX
**** Echanges atomiques sur le Komodo BarterDEX
**** Introduction, Alice et Bob
**** Alice et Bob font un marché
**** Mesures incitatives et dissuasives pour maintenir un bon comportement
**** Détails supplémentaires sur l'échange atomique BarterDEX
*** Une explication plus détaillée du processus de connexion d'échange atomique
**** Les frais DEX : <dexfee>
**** L'API BarterDEX
**** Une brève discussion sur le futur de BarterDEX
* Jumblr la fonctionnalité native Komodo pour la vie privée
** Résumé (Jumblr)
*** Introduction
**** L'option de la protection de la vie privée est essentielle à l'écosystème de Komodo
**** Défis pour les systèmes centrés sur la confidentialité et la solution Komodo
*** La solution Komodo
**** Une introduction à Jumblr
**** Une brève explication des deux technologies fondamentales
*** Le processus Jumblr
**** Anonymisation de pièces Komodo native (KMD)
**** Actions utilisateur 
*** Couches de sécurité additionnelles
**** Le processus de rupture de fonds de Jumblr
**** Le processus de Jumblr de déplacer les lots individuels vers une adresse privée
*** Considérations de confidentialité supplémentaires
**** L'attaque chronométrique
**** L'attaque de sac à dos
**** Autres améliorations de la sécurité pour lutter contre les attaques de synchronisation et de sac à dos
*** Offrir la confidentialité à d'autres crypto-monnaies
**** Le processus Jumblr actuel : trading manuel non-KMD vers trading sur BarterDEX
**** Capacités futures : Jumblr automatise le processus de négociation BarterDEX pour l'utilisateur
*** Un mot sur les risques inhérents à Jumblr et à l'écosystème de Komodo
*** Jumblr fournit à l'écosystème de Komodo la confidentialité
* Information supplémentaire selon l'écosystème Komodo
** Notes finales concernant le projet Komodo
*** Crypto-monnaies à taux fixe 
*** Contrats intelligents sur la plateforme Komodo 
**** Contrats intelligents basés sur le protocole Bitcoin
**** Conditions cryptographiques, racine Merkle de la racine Merkle (MoM: Merkle Root of Merkle Root) et chaînes d'actifs personnalisées
**** Détails concernant la chaîne primaire de l'écosystème de Komodo : KMD
**** Conclusion 
** Rémerciements et références
* Liens pour collaborer
  1. La vidéo explicative : [[https://youtu.be/L1IU06G9TUE]]
  2. Rejoindre le groupe [[https://t.me/joinchat/JGxHIxMP5cWHHVDjxpcATQ][Telegram]] pour la répartition des tâches
* Ressources complémentaires
  1. [[https://youtu.be/ooJCp3YTLKk][2017-06-29]]
  2. [[https://youtu.be/INVxFEWo6VI][2017-09-23]]
  3. [[https://youtu.be/bUja6AOL05w][2017-10-03]]
  4. [[https://youtu.be/GUzpzgfvTlg][2017-10-18]]
  5. [[https://youtu.be/wnKAfgv_g9M][2017-10-29]]
  6. [[https://youtu.be/epwgFAZj0z0][2017-11-06]]
  7. [[https://youtu.be/BSXTWOx10vI][2017-12-23]]
  8. [[https://youtu.be/O1_K4JAiomo][2017-12-26]]
  9. [[https://youtu.be/Y_AiDg1o2Ns][2018-08-16]]
 10. [[https://youtu.be/C0KWm3h2fFM][2018-09-14]]
 11. 

* Footnotes

[fn:2] https://en.wikipedia.org/wiki/Bitcoin_network

[fn:1] https://en.wikipedia.org/wiki/Enigma_machine
