#+TITLE: [[https://komodoplatform.com/wp-content/uploads/2018/06/Komodo-Whitepaper-June-3.pdf][Papier blanc de la crypto Komodo]]
#+AUTHOR: Laurent Garnier

* Introduction à Komodo 
  Le projet Komodo vise à donner aux utilisateurs la liberté de passer
  par la technologie blockchain. Il existe de nombreuses formes de
  liberté que Komodo peut offrir, et nous nous concentrons
  actuellement sur l’autonomisation de deux types d’utilisateurs :
  l’entrepreneur de la chaîne de blocs et l’investisseur moyen de
  crypto-monnaie. Ensemble, notre communauté d’entrepreneurs,
  d’investisseurs et d’autres utilisateurs forme un écosystème
  économique. 

  Le pilier fondamental de l'écosystème de Komodo est la
  sécurité. Komodo fournit une forme de sécurité unique et innovante
  qui est aussi forte que le réseau Bitcoin, mais ne nécessite pas le
  coût incroyable. Chaque membre de l'écosystème de Komodo bénéficie
  des avantages de cette sécurité. L'investisseur en dépend pour un
  usage quotidien. L'entrepreneur compte sur lui pour protéger son
  innovation de blockchain à un coût abordable, même pour les petites
  entreprises et les startups. 

  Une autre des technologies puissantes de Komodo est une nouvelle
  méthode de trading de cryptomonnaies directement d’une personne à
  une autre. C’est un nouveau type d’«échange décentralisé». Notre
  échange décentralisé supprime toutes les formes d’intermédiaires, de
  bons et de services de dépôt fiduciaire. Il s'appuie sur un concept
  sous-jacent appelé «échange atomique» et nous sommes les meneurs de
  cette technologie.

  Notre échange décentralisé alimenté par un échange atomique sert à
  la fois l'investisseur et l'entrepreneur de la chaîne de blocs.

  Pour l'investisseur, ils peuvent négocier des devises sans avoir à
  passer par un échange centralisé, ce qui peut être un processus ardu
  et même dangereux. Ils n'ont pas non plus besoin d'utiliser un
  service de dépôt fiduciaire, un bon d'achat, ni même une pièce de
  monnaie intermédiaire, même pas de Bitcoin. De plus, il n'y a pas de
  processus d'enregistrement requis, ni de limites de retrait. Nous
  prenons actuellement en charge environ 95% des cryptomonnaies
  existantes, y compris les pièces basées sur le protocole Bitcoin,
  les jetons Ethereum et les jetons ERC20 basés sur Ethereum. 

  Pour l'entrepreneur, notre échange décentralisé permet de lancer de
  nouveaux produits dans le monde sans implication des
  intermédiaires. De plus, même les entrepreneurs qui ont déjà
  construit d’autres projets de blockchain en dehors de notre
  écosystème peuvent facilement mettre leur pièce sur notre échange
  décentralisé. La seule exigence est que le produit blockchain ait
  les éléments de sécurité appropriés au cœur du code de la
  blockchain. 

  Komodo intègre également de puissantes fonctionnalités de
  confidentialité dans notre plate-forme. Cela permet à l'investisseur
  d'échanger et d'acheter des biens et services dans le cadre de son
  droit à la vie privée. Cela permet également à l'entrepreneur de
  libérer son produit et de créer des sources de financement auprès
  d'un public qui préfère conserver cette confidentialité.

  Il existe de nombreuses autres technologies et fonctionnalités dans
  l'écosystème de Komodo, et nous assistons à une croissance rapide
  des entrepreneurs et des investisseurs. 

  Ce livre blanc de Komodo propose une discussion approfondie sur les
  fonctions de sécurité uniques de Komodo, notre échange décentralisé,
  la méthode de diffusion des nouveaux produits et nos fonctionnalités
  de confidentialité natives.

  Nous accueillons les commentaires de nos lecteurs. Si vous avez des
  questions ou des préoccupations concernant la lecture de ce
  document, veuillez contacter directement notre équipe. Vous pouvez
  trouver nos coordonnées sur notre site Web d'accompagnement : [[https://komodoplatform.com/]]

* Méthode de sécurité Komodo : preuve de travail différé (DPOW : Delayed Proof Of Work)
** Une discussion fondamentale de la sécurité d'une blockchain
   La forme de sécurité de Komodo s'appelle la technologie de preuve
   de travail différée (dPoW). Il s'appuie sur la forme la plus
   avancée de sécurité de la chaîne de blocs existante, la technologie
   de preuve de travail (PoW). Cette dernière forme de sécurité est la
   méthode utilisée par le réseau Bitcoin. Pour comprendre la valeur
   de la sécurité dPoW de Komodo, nous devons d'abord expliquer
   comment PoW fonctionne et pourquoi il s'agit de la méthode la plus
   sécurisée de maintenance d'une blockchain décentralisée. Nous
   devons également examiner les lacunes de PoW, afin que nous
   puissions comprendre la nécessité de la méthode dPoW de Komodo et
   les avantages qu'elle apporte à la communauté de la blockchain. 

   Pour comprendre comment fonctionne la technologie PoW, nous
   commençons par expliquer les racines qui font du protocole Bitcoin
   un moyen viable de transférer de la valeur en toute sécurité. 


*** Qu'est-ce qu'un mécanisme de consensus ?
**** Le problème de "double dépense"

     La création de la technologie de la chaîne de blocs découle des
     premières études mathématiques du cryptage utilisant la
     technologie informatique. 

     L'un de ces exemples concerne le dispositif de codage de
     l'information "Enigma", inventé par les Allemands à la fin de la
     Première Guerre mondiale. Alan Turing, un agent britannique de
     renseignement, a battu le dispositif Enigma en inventant le
     premier «ordinateur numérique» au monde. This provided enough
     computing power to break Enigma's encryption and discover the
     German secret communications[fn:1].

     Cette première affaire de cryptage a déclenché une course à
     travers le monde pour développer une myriade de formes de
     transfert sécurisé des informations d'un pary à l'autre via la
     technologie informatique. Bien que chaque nouvelle forme de
     chiffrement informatique offrait davantage d’avantages, il
     restait un problème qui empêchait le chiffrement d’être utile
     pour transférer non seulement des informations, mais aussi une
     valeur financière.

     Ce problème est connu sous le nom de problème de «double
     dépense». Le problème réside dans la capacité des ordinateurs à
     dupliquer sans cesse les informations. Dans le cas de la valeur
     financière, il y a trois choses importantes à noter: qui possède
     une valeur spécifique; l'heure à laquelle la personne possède
     cette valeur; l'adresse du portefeuille dans lequel réside la
     valeur. Lors du transfert de valeur financière d’une personne à
     une autre, il est essentiel que si la personne A envoie de
     l’argent à la personne B, la personne A ne soit pas en mesure de
     reproduire le même montant et de le renvoyer à la personne C. 

     Le protocole Bitcoin[fn:2], inventé par une personne anonyme (ou des
     personnes) revendiquant le nom de Satoshi Nakamoto, a résolu le
     problème des doubles dépenses. Le code mathématique et
     informatique sous-jacent est à la fois très complexe et
     innovant. Pour les besoins de cet article, nous devons seulement
     nous concentrer sur le seul aspect du protocole Bitcoin qui
     résout le problème des doubles dépenses: le mécanisme de
     consensus. 

     

**** Le mécanisme de consensus fournit une sécurité contre une "double dépense"
     Le mécanisme de consensus inventé par Nakamoto est peut-être
     l’une des innovations les plus puissantes du XXIe siècle. Son
     invention permet à des appareils individuels de fonctionner
     ensemble, en utilisant des niveaux de cryptage élevés, de suivre
     en toute sécurité et avec précision la propriété de la valeur
     numérique (qu'il s'agisse de ressources financières, de biens
     immobiliers numériques, etc.). Il effectue cela d'une manière qui
     ne permet à personne sur le même réseau (c'est-à-dire Internet)
     de dépenser deux fois la même valeur. 

     Supposons qu'un utilisateur, Alice, indique dans son portefeuille
     numérique qu'elle souhaite envoyer de l'argent cryptomonnaie à un
     ami. L’ordinateur d’Alice rassemble maintenant plusieurs
     informations, y compris les autorisations et mots de passe
     nécessaires, le montant que Alice veut dépenser et l’adresse de
     réception du portefeuille de son ami. Toutes ces informations
     sont rassemblées dans un paquet de données, appelé "transaction",
     et l’appareil d’Alice envoie la transaction sur Internet. 

     Il existe plusieurs types d’appareils qui interagissent avec la
     transaction d’Alice sur l'Internet. Ces périphériques partageront
     les informations sur les transactions avec d'autres périphériques
     prenant en charge le réseau de cryptomonnaie. Pour cette
     discussion, nous devons seulement nous concentrer sur un type de
     périphérique: un mineur de crypto-monnaie. 

     Note : Les descriptions suivantes sont des explications
     simplifiées d'un processus byzantin vraiment complexe. Il existe
     de nombreuses autres stratégies que les mineurs de crypto-monnaie
     conçoivent pour dépasser leur concurrence, et ces stratégies
     peuvent varier considérablement.


**** Un mineur est en compétition pour ajouter des blocs à l'historique du réseau avec une récompense en retour
***** Etape 1 : Préparation de l'information préliminaire

      Cet appareil effectue une activité appelée "minage" de
      crypto-monnaie. Concentrons-nous maintenant sur un périphérique
      de minage qui capture les données de transaction brutes
      d’Alice. Cet appareil appartient à un mineur averti, nommé Bob,
      qui souhaite ajouter la transaction d’Alice à l’historique
      permanent du réseau Bitcoin. 

      Si Bob est la première personne à traiter correctement la
      transaction d’Alice, il recevra une récompense financière. Un
      élément clé de cette récompense est un pourcentage basé sur le
      montant total de la transaction d’Alice. 
***** Le Mempool est la collection de toutes les transactions brutes en attente de traitement
      De plus, Bob n’a pas une seule transaction à effectuer. Il a
      plutôt un pool complet de transactions brutes, créées par de
      nombreuses personnes sur Internet. Les données brutes de chacune
      de ces transactions se trouvent dans la banque de mémoire locale
      du dispositif d’extraction de chaque mineur, en attente des
      commandes du mineur. Les mineurs appellent cette pool de
      transactions, le "mempool". La plupart des mineurs ont des
      systèmes automatisés pour déterminer le processus de sélection
      des transactions, en fonction du bénéfice estimé.
***** Création des hashs de transaction
      Après que Bob ait fait ses choix quant aux transactions qu’il
      tentera de miner (et nous supposons qu'il inclut la transaction
      d'Alice), l'appareil de minage de Bob commence alors une série
      de calculs. 

      Son appareil prendra d’abord les données brutes de chaque
      transaction et utilisera des formules mathématiques pour
      compresser la transaction dans un format plus petit et plus
      facile à gérer. Cette nouvelle forme est appelée un "hash de
      transaction"[fn:3]. Par exemple, le hachage de transaction
      d’Alice pourrait ressembler à ceci : 

      #+BEGIN_CENTER
      *b1fea52486ceoc62bb442b53oa3f0132b826c74e473d1f2c220bfa78111c5082*
      #+END_CENTER

      Bob préparera potentiellement des centaines de hachages de
      transaction avant de passer à l'étape suivante. Une chose
      importante à comprendre à propos de la compression des données
      dans le protocole Bitcoin, y compris le hachage de transaction
      ci-dessus, est que les calculs ci-après obéissent à un principe
      appelé, l'effet de cascade. 
***** L'effet en cascade : la modification d'un bit de données modifie le résultat entier
      L'effet de cascade signifie simplement que si Bob tentait de
      modifier le plus petit bit des données brutes, que ce soit par
      souci de tricher, par erreur ou pour toute autre raison, le
      hachage de la transaction changerait radicalement. De cette
      manière, les formules mathématiques du protocole Bitcoin
      garantissent que Bob ne peut pas créer un historique incorrect. 

      Si Bob tentait de créer un hachage de transaction incorrect, les
      autres mineurs du réseau pourraient utiliser les données de
      transaction brutes d’Alice, effectuer les calculs formules de
      base du protocole Bitcoin, et découvrir immédiatement que les
      hashes de Bob sont incorrects. Ainsi, tous les périphériques du
      réseau rejetteraient les tentatives incorrectes de Bob et
      l’empêcheraient de réclamer des récompenses. 
***** Première étape (suite) : fin des calculs préliminaires
      Maintenant, en utilisant plus de formules mathématiques, Bob
      prend les hachages de transaction qu'il essaie de traiter et les
      compresse en un nouveau morceau de données gérable. 

      C'est appelé la "racine de merkel". Il représente toutes les
      transactions que Bob espère traiter et dont il espère obtenir
      une récompense. La racine de merkle de Bob pourrait ressembler à
      ceci

      #+BEGIN_CENTER
      *7dac2c5666815c17a3b36427de37bb9d2e2c5ccec3f8633eb91a4205cb4c10*
      #+END_CENTER
      

      Enfin, Bob rassemblera les informations fournies par le dernier
      mineur qui a été ajouté à l’historique de la blockchain
      permanente. Cette information s'appelle "l'en-tête du bloc". Il
      contient une grande quantité de données complexes et nous
      n’entrerons pas dans tous les détails. Le seul élément important
      à noter est que l'en-tête de bloc donne à Bob des indices sur la
      manière d'ajouter correctement le prochain élément d'information
      à l'historique permanent de Bitcoin. Un de ces conseils pourrait
      ressembler à ceci :

      #+BEGIN_CENTER
      *"difficulty" : 1.00000000*
      #+END_CENTER

      Nous reviendrons là-dessus plus tard.

      Ayant toutes ces informations, Bob est presque prêt. Sa
      prochaine étape est où le vrai le défi commence. 
***** Etape deux : la course pour finir premier
      L’ordinateur de Bob va collecter toutes les informations
      ci-dessus et les collecter dans un ensemble de données appelé
      "bloc". L'extraction de ce bloc et l'ajout à la liste des blocs
      qui ont précédé est le processus de création d'une "chaîne" de
      blocs, d'où le nom de l'industrie "blockchain". 

      Cependant, ajouter des blocs à la blockchain n'est pas si
      simple. Bien que Bob ait déjà tout préparé correctement, le
      protocole Bitcoin ne donne pas encore à Bob le droit d'ajouter
      son bloc proposé à la chaîne. 

      Le mécanisme de consensus est conçu pour forcer les mineurs à se
      battre pour ce droit. En exigeant que les mineurs travaillent
      pour le droit d'exploiter un nouveau bloc valide, la concurrence
      se propage à travers le réseau. Cela offre de nombreux
      avantages, notamment le temps nécessaire aux transactions des
      utilisateurs (comme Alice) pour diffuser dans le monde entier,
      offrant ainsi un niveau de décentralisation au réseau.
      
      Par conséquent, bien que Bob préfère créer immédiatement un
      nouveau bloc valide et collecter sa récompense, il ne le peut
      pas. Il doit gagner la compétition en effectuant le bon travail
      en premier. C'est la source du titre du mécanisme de consensus
      du protocole Bitcoin, "Proof of Work" (PoW)[fn:4]. 

      Le concours que doit remporter Bob est d'être le premier à
      trouver une réponse à un simple puzzle mathématique conçu par
      Satoshi Nakamoto. Pour résoudre le casse-tête, Bob devine des
      nombres aléatoires jusqu'à ce qu'il découvre un nombre
      correct. Le nombre correct est déterminé par les formules
      complexes internes du mécanisme de consensus et ne peut être
      découvert par aucun autre moyen que de deviner. Les mineurs de
      bitcoins appellent ce numéro un "nonce", qui est l'abréviation
      d'un "numéro" que vous utilisez "une fois". "[fn:5] 

      L'appareil de minage de Bob fera des suppositions aléatoires au
      nonce, l'une après l'autre, jusqu'à ce qu'un nonce correct soit
      trouvé. À chaque tentative, Bob insérera d'abord le nonce
      proposé dans le reste de son bloc. Pour savoir si sa supposition
      est correcte, il utilisera ensuite des formules mathématiques
      (comme celles qu’il a utilisées précédemment) pour compresser sa
      tentative dans un "hash de bloc".

      Un hachage de bloc est une forme de données petite et gérable
      qui représente l’historique complet de la chaîne de blocs
      Bitcoin et toutes les informations du bloc proposé par Bob. Un
      hash de bloc peut ressembler à ceci :

      #+BEGIN_CENTER
      *oooooooooo19d6689co85ae165831e934ff763ae46a2a6c172b3f1b6oa8ce*
      #+END_CENTER

      Rappelez-vous maintenant l'effet Cascade, et comment il indique
      que la modification d'un petit nombre dans les données avant
      d'effectuer les calculs mathématiques crée un résultat très
      différent.

      Puisque Bob inclut continuellement de nouvelles suppositions au
      nonce à chaque calcul d'un hash de bloc, chaque tentative de
      hash de bloc produira une séquence de nombres.

      Les mineurs du réseau Bitcoin savent quand un mineur, tel que
      Bob, résout le problème. en observant les indices fournis
      précédemment. Rappelez-vous que la dernière fois qu'un mineur a
      ajouté des données à la blockchain, il a fourni ces indices dans
      son en-tête de bloc. L'un des indices de l'en-tête de bloc
      précédent peut ressembler à ceci :      

      #+BEGIN_CENTER
      *"difficulty" : 1.00000000*
      #+END_CENTER

      Ce détail, "difficulty", indique simplement aux mineurs combien
      de zéros devraient figurer au début du prochain hachage de bloc
      valide. Lorsque le niveau de difficulté est le niveau affiché
      ci-dessus, il indique aux mineurs qu'il doit y avoir exactement
      dix zéros. 

      Observez de nouveau le hachage de bloc de Bob, créé après avoir
      deviné un nonce, en ajoutant ce nonce proposé dans son bloc et
      en exécutant les formules mathématiques suivantes :

      #+BEGIN_CENTER
      *000000000019d6689co85ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f*
      #+END_CENTER

      Le hachage de bloc ci-dessus a dix zéros au début, ce qui
      correspond au nombre de zéros dans le niveau de difficulté.

      Par conséquent, le hash proposé par Bob est correct. Cela doit
      signifier qu'il a deviné un nonce correct. Tous les mineurs du
      réseau peuvent prouver que Bob était correct en prenant toutes
      les mêmes informations à partir de leurs mempools, en ajoutant
      le nonce de Bob et en effectuant les calculs mathématiques. Ils
      recevront le même résultat et par conséquent, Bob est le gagnant
      de cette manche.

      En revanche, en raison de l’effet Cascade, si la tentative de
      Bob de nonce avait produit un hachage de bloc avec le nombre
      incorrect de zéros au début, son hachage de bloc serait
      invalide. Le réseau ne lui donnerait pas le droit d'ajouter un
      hachage de bloc incorrect au réseau et tous les mineurs
      continueraient à chercher. 

***** Etape trois : Bob trouve le nonce

      Une fois qu'un mineur découvre un nonce qui produit un hachage
      de bloc valide, le mineur a "trouvé un nouveau bloc" et peut
      envoyer le signal sur Internet. Le mécanisme de consensus
      fonctionnant sur tous les autres appareils de minage peut vérifier
      lui-même les calculs. Une fois vérifié, le mécanisme de
      consensus accorde au mineur le droit d'ajouter le bloc proposé à
      la blockchain et de recevoir la récompense. 

      Revenons à la machine de Bob, ayant juste deviné un nonce
      correct, et tenant ainsi un hachage de bloc valide. La machine
      de Bob envoie instantanément les informations gagnantes sur
      Internet, et Bob collecte sa récompense sur le réseau Bitcoin. 

      Tous les autres mineurs doivent se réajuster. Auparavant, ils
      cherchaient le nonce correct basé sur les informations de
      l'en-tête de bloc précédent. Cependant, le nouveau bloc valide
      de Bob inclut un nouvel en-tête de bloc. Tous les autres mineurs
      du réseau abandonnent leur travail actuel, adoptent le nouvel
      en-tête de bloc de Bob, effectuent de nombreux recalculs dans
      leurs données sous-jacentes et commencent leur recherche du
      prochain nonce. 

      Le protocole Bitcoin ne présente aucune sympathie pour les
      efforts inutiles d’un mineur. Supposons qu'une autre machine du
      réseau essaie également d’exploiter la transaction d’Alice et
      qu’elle se soit inclinée devant Bob dans la course. Seul Bob
      gagne la récompense de la transaction d’Alice et l’autre mineur
      ne reçoit rien en échange de leurs coûts et de son temps.
      
      Pour Alice, ce processus semble simple. Elle a d'abord indiqué
      l'adresse de portefeuille de son amie et envoyé la
      crypto-monnaie. Après un certain temps, son amie a reçu
      l'argent. Alice peut ignorer le processus byzantin des mineurs
      entre ces deux événements. Alice ne s'en rend peut-être pas
      compte, mais le mécanisme de consensus de la preuve de travail
      constitue le fondement de la sécurité sur lequel elle s'appuie.
      

** La preuve de travail est la forme la plus sécurisée des mécanismes de consensus
*** La vitesse et la puissance sont l'essence
**** L'effet de réseau : la capacité de Bitcoin à dominer commence
*** La règle de la chaîne la plus longue : la "sauce secrète" de la domination PoW (Proof of Work: preuve de travail)
**** Les effets simples de la règle de la plus longue chaîne
**** Le compte des deux blockchains
**** Un conflit d'intérêt interne survient avec le réseau Bitcoin 
**** La règle de la plus longue chaîne : l'historique qui est le plus long en premier, gagne
*** La façon "simple"  de détruire un réseau PoW : l'attaque des 51%
*** La taille est une autre raison derrière le succès actuel de Bitcoin parmi les réseaux PoW
*** La façon "dure" de détruire un réseau PoW : l'attaque de la génèse (Genesis Attack)
**** Une attaque de la génèse sur le réseau Bitcoin
**** Les dangers plus réalistes de l'attaque de la génèse
*** Les problèmes financiers et environnementaux avec tous les réseaux PoW
**** Les réseaux PoW coûtent chers
**** Les mineurs sont libres de miner d'autres réseaux
**** Le premier mécanisme de consensus alternatif : preuve de part ou preuve d'enjeu (Proof of Stake)
**** Les risques de sécurité et les défauts de PoS
**** Un résumé du mécanisme de consensus PoW
** La solution Komodo
*** Résumé du mécanisme de consensus sur la preuve de travail différée (dPoW)
**** Une note sur la technologie Iguana Core de Komodo
**** Une brève discussion sur la sécurité assurée par les noeuds notaires
*** Le processus de notarisation
**** Comprendre les incitations économique et sécuritaire dans le réseau dPoW Komodo
*** Mesures de protection de Komodo en action 
**** Les notarisations fournissent une défense contre l'attaque de 51% et l'attaque de la genèse.
*** Le mécanisme de consensus dPoW est inhérent à tous les actifs des chaînes Komodo

* Les ICO décentralisées (DICO : Decentralized Initial Coin Offering)
** Résumé des DICO
*** Les défis dans les plateformes ICO actuelles
*** Faiblesses spécifiques dans le modèle centralisé ICO
*** Discrimination de tiers via les ICO centralisées
*** Centralisation des technologies ICO : baleines, pirates, et erreurs humaines
*** Pirates et erreurs humaines
** La solution Komodo 
*** Les DICO
*** Le processus de création d'une nouvelle blockchain dans l'écosystème Komodo 
**** La première commande pour créer une nouvelle pièce 
*** Les fonctionnalités de la nouvelle chaîne d'actif
*** Générer et miner les pièces
**** L'approvisionnement total en pièces est distribué dans le bloc de la génèse
*** Notarisation de la chaîne Komodo principale
*** La distribution des pièces 
**** Les essais et les déplacements de la méthode ICO centralisée
*** Entrer dans les dICO
**** Alimenté par les technologies Komodo BarterDEX et Jumblr
**** Les nombreuses solutions du modèle dICO: sécurité, confidentialité, décentralisation et liberté.
* Barterdex place de marché décentralisée ou la puissance d'échange atomique Komodo
** Résumé (BarterDEX)
*** Introduction
**** Les débuts et les voyages des échanges décentralisés
**** BarterDEX : une solution complète
**** Améliorations récentes dans BarterDEX
*** Technologie BarterDEX
**** Correspondance d'ordre
**** Correspondance des commandes avec les nœuds à relais complet et sans relais
**** La technologie Jumblr ajoute de l'intimité
**** Iguana Core fournit la base de notre fonctionnalité "adresse intelligente ("Smart Address")
*** Les UTXO : un concept insaisissable, mais fondamental.
**** Comparaison entre les UTXO et les monnaies fiat
**** Compréhension des crypto-monnaies et leurs UTXOs
*** Trading sur BarterDEX 
**** Comment BarterDEX traite les offres de commande et les UTXOs
*** Explications détaillées du processus BarterDEX
**** Echanges atomiques sur le Komodo BarterDEX
**** Introduction, Alice et Bob
**** Alice et Bob font un marché
**** Mesures incitatives et dissuasives pour maintenir un bon comportement
**** Détails supplémentaires sur l'échange atomique BarterDEX
*** Une explication plus détaillée du processus de connexion d'échange atomique
**** Les frais DEX : <dexfee>
**** L'API BarterDEX
**** Une brève discussion sur le futur de BarterDEX
* Jumblr la fonctionnalité native Komodo pour la vie privée
** Résumé (Jumblr)
*** Introduction
**** L'option de la protection de la vie privée est essentielle à l'écosystème de Komodo
**** Défis pour les systèmes centrés sur la confidentialité et la solution Komodo
*** La solution Komodo
**** Une introduction à Jumblr
**** Une brève explication des deux technologies fondamentales
*** Le processus Jumblr
**** Anonymisation de pièces Komodo native (KMD)
**** Actions utilisateur 
*** Couches de sécurité additionnelles
**** Le processus de rupture de fonds de Jumblr
**** Le processus de Jumblr de déplacer les lots individuels vers une adresse privée
*** Considérations de confidentialité supplémentaires
**** L'attaque chronométrique
**** L'attaque de sac à dos
**** Autres améliorations de la sécurité pour lutter contre les attaques de synchronisation et de sac à dos
*** Offrir la confidentialité à d'autres crypto-monnaies
**** Le processus Jumblr actuel : trading manuel non-KMD vers trading sur BarterDEX
**** Capacités futures : Jumblr automatise le processus de négociation BarterDEX pour l'utilisateur
*** Un mot sur les risques inhérents à Jumblr et à l'écosystème de Komodo
*** Jumblr fournit à l'écosystème de Komodo la confidentialité
* Information supplémentaire selon l'écosystème Komodo
** Notes finales concernant le projet Komodo
*** Crypto-monnaies à taux fixe 
*** Contrats intelligents sur la plateforme Komodo 
**** Contrats intelligents basés sur le protocole Bitcoin
**** Conditions cryptographiques, racine Merkle de la racine Merkle (MoM: Merkle Root of Merkle Root) et chaînes d'actifs personnalisées
**** Détails concernant la chaîne primaire de l'écosystème de Komodo : KMD
**** Conclusion 
** Rémerciements et références
* Liens pour collaborer
  1. La vidéo explicative : [[https://youtu.be/L1IU06G9TUE]]
  2. Rejoindre le groupe [[https://t.me/joinchat/JGxHIxMP5cWHHVDjxpcATQ][Telegram]] pour la répartition des tâches
* Ressources complémentaires
  1. [[https://youtu.be/ooJCp3YTLKk][2017-06-29]]
  2. [[https://youtu.be/INVxFEWo6VI][2017-09-23]]
  3. [[https://youtu.be/bUja6AOL05w][2017-10-03]]
  4. [[https://youtu.be/GUzpzgfvTlg][2017-10-18]]
  5. [[https://youtu.be/wnKAfgv_g9M][2017-10-29]]
  6. [[https://youtu.be/epwgFAZj0z0][2017-11-06]]
  7. [[https://youtu.be/BSXTWOx10vI][2017-12-23]]
  8. [[https://youtu.be/O1_K4JAiomo][2017-12-26]]
  9. [[https://youtu.be/Y_AiDg1o2Ns][2018-08-16]]
 10. [[https://youtu.be/C0KWm3h2fFM][2018-09-14]]
 11. 

* Footnotes

[fn:5] NdT : /'number' you use 'once'/ => nonce

[fn:4] NdT : preuve de travail

[fn:3] NdT : on peut voir ça comme une signature

[fn:2] https://en.wikipedia.org/wiki/Bitcoin_network

[fn:1] https://en.wikipedia.org/wiki/Enigma_machine
